baseURL = "https://raybuhr.github.io/"
languageCode = "en-us"
title = "the raybuhr blog"
theme = "gohugo-theme-ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "the raybuhr blog"
  twitter = "https://twitter.com/raybuhr"
  github = "https://github.com/raybuhr"
  linkedin = "https://www.linkedin.com/in/raybuhr"
  background_color_class = "bg-black"
  featured_image = "/images/blog_bg.jpg"
