title = "the ray buhr blog"
baseURL = "/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The Personal Blog of Ray Buhr"
  twitter = "https://twitter.com/raybuhr"
  github = "raybuhr"
  linkedin = "raybuhr"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-grey"
  featured_image = "/images/blog_bg.jpg"
  recent_posts_number = 5
