title = "the ray buhr blog"
baseURL = "//raybuhr.github.io/blog/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true
pygmentsUseClassic = true
relativeURLS = true
canonifyurls = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The Personal Blog of Ray Buhr"
  twitter = "https://twitter.com/raybuhr"
  github = "https://github.com/raybuhr"
  linkedin = "https://www.linkedin.com/in/raybuhr"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  body_classes = "avenir bg-near-white"
  featured_image = "/images/blog_bg.jpg"
  recent_posts_number = 5
